### ISSUE TITLE
Multiple Unmapped Properties in a single UnmappedProperty

### ISSUE THREAD

**Issue by p3t3rix** [oliverhanappi/ManualMappingGuard#1]
It would be be good for readability if the [UnmappedProperty]-Attribute would allow multiple strings instead of only one.

**Comment by oliverhanappi** [comment]
That's a great idea. We could probably do something like this:

```csharp
[UnmappedProperties("Id", "Tag", ...)]
public Model Map(...)
{
  ...
}
```

What do you think? I would keep the UnmappedProperty attribute for compatibility.

**Comment by p3t3rix** [comment]
Sounds good!

**Comment by oliverhanappi** [comment]
Version `1.1.0` is out and available on nuget.org: https://www.nuget.org/packages/ManualMappingGuard/1.1.0

**Comment by p3t3rix** [comment]
Wow that was fast! Thanks :)
